#!/usr/bin/env bash
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /usr/share/nginx/html/index.html
sudo cp /usr/share/nginx/html/index.html /var/www/html/index.nginx-debian.html
sudo service nginx restart
