#!/usr/bin/env bash
# Install nginx
apt-get -y update
apt-get -y install nginx
sudo chown ubuntu /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
systemctl restart nginx
