#!/usr/bin/env bash
# redirect /redirect_me 
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /usr/share/nginx/html/index.html
sudo cp /usr/share/nginx/html/index.html /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
