#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd
while IFS= read -r line
do
	Username=$(echo "$line" | cut -d ':' -f 1)
	Password=$(echo "$line" | cut -d ':' -f 2)
	User_ID=$(echo "$line" | cut -d ':' -f 3)
	Group_ID=$(echo "$line" | cut -d ':' -f 4)
	User_ID_Info=$(echo "$line" | cut -d ':' -f 5)
	Home_directory=$(echo "$line" | cut -d ':' -f 6)
	Command_shell=$(echo "$line" | cut -d ':' -f 7)
	
	echo "The user $Username is part of the $Group_ID gang, lives in $Home_directory and rides $Command_shell. $User_ID place is protected by the passcode $Password, more info about the user here: $User_ID_Info"
done < "/etc/passwd" 
