#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0
while [ $i -ne 10 ]
do
	if [ $i == 3 ]
	then
		echo "bad luck"
		(( i = i + 1 ))
	elif [ $i == 7 ]
	then
		echo "good luck"
		(( i = i + 1 ))
	else
		echo "Best School"
		(( i = i + 1 ))
	fi
done
