#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20
i=1
while [ $i -ne 21 ]
do
	if [ $i == 4 ]
	then
		echo "$i"
		echo "bad luck from China"
		(( i = i + 1 ))
	elif [ $i == 9 ]
	then
		echo "$i"
		echo "bad luck from Japan"
		(( i = i + 1 ))
	elif [ $i == 17 ]
	then
		echo "$i"
		echo "bad luck from Italy"
		(( i = i + 1 ))
	else
		echo "$i"
		(( i = i + 1 ))
	fi
done
